version: '3.8'

services:

  mssql:

    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: mssql-lab

    environment:

      ACCEPT_EULA: "Y"

      SA_PASSWORD: "Str0ngP@ssword!"

      MSSQL_PID: "Developer"

    volumes:

      - mssql_data:/var/opt/mssql

    networks:

      - labnet

  backend:

    build: ./backend

    container_name: backend-app

    depends_on:

      - mssql

    environment:

      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=lab_tracker;encrypt=false;trustServerCertificate=true

      SPRING_DATASOURCE_USERNAME: sa

      SPRING_DATASOURCE_PASSWORD: Str0ngP@ssword!

    ports:

      - "8080:8080"

    networks:

      - labnet

networks:

  labnet:

volumes:

  mssql_data:

